# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spatial_dynamics.ui'
#
# Created: Mon Nov 28 19:26:43 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_spatial_dynamics(object):
    def setupUi(self, spatial_dynamics):
        spatial_dynamics.setObjectName(_fromUtf8("spatial_dynamics"))
        spatial_dynamics.resize(400, 538)
        spatial_dynamics.setWindowTitle(QtGui.QApplication.translate("spatial_dynamics", "Spatial Dynamics", None, QtGui.QApplication.UnicodeUTF8))
        spatial_dynamics.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.inputweightslabel = QtGui.QLabel(spatial_dynamics)
        self.inputweightslabel.setGeometry(QtCore.QRect(20, 340, 111, 16))
        self.inputweightslabel.setText(QtGui.QApplication.translate("spatial_dynamics", "Input Spatial Weights", None, QtGui.QApplication.UnicodeUTF8))
        self.inputweightslabel.setObjectName(_fromUtf8("inputweightslabel"))
        self.inputweightsline = QtGui.QLineEdit(spatial_dynamics)
        self.inputweightsline.setGeometry(QtCore.QRect(130, 340, 221, 20))
        self.inputweightsline.setObjectName(_fromUtf8("inputweightsline"))
        self.inputweightsbutton = QtGui.QPushButton(spatial_dynamics)
        self.inputweightsbutton.setGeometry(QtCore.QRect(360, 340, 31, 23))
        self.inputweightsbutton.setText(QtGui.QApplication.translate("spatial_dynamics", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.inputweightsbutton.setObjectName(_fromUtf8("inputweightsbutton"))
        self.inputweightscreate = QtGui.QPushButton(spatial_dynamics)
        self.inputweightscreate.setGeometry(QtCore.QRect(130, 370, 75, 23))
        self.inputweightscreate.setText(QtGui.QApplication.translate("spatial_dynamics", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.inputweightscreate.setObjectName(_fromUtf8("inputweightscreate"))
        self.outputgroupbox = QtGui.QGroupBox(spatial_dynamics)
        self.outputgroupbox.setGeometry(QtCore.QRect(10, 390, 381, 111))
        self.outputgroupbox.setTitle(QtGui.QApplication.translate("spatial_dynamics", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.outputgroupbox.setObjectName(_fromUtf8("outputgroupbox"))
        self.matrixcheckbox = QtGui.QCheckBox(self.outputgroupbox)
        self.matrixcheckbox.setGeometry(QtCore.QRect(20, 20, 131, 16))
        self.matrixcheckbox.setText(QtGui.QApplication.translate("spatial_dynamics", "Transition Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.matrixcheckbox.setObjectName(_fromUtf8("matrixcheckbox"))
        self.probabilitiescheckbox = QtGui.QCheckBox(self.outputgroupbox)
        self.probabilitiescheckbox.setGeometry(QtCore.QRect(200, 20, 161, 16))
        self.probabilitiescheckbox.setText(QtGui.QApplication.translate("spatial_dynamics", "Transition Probabilities", None, QtGui.QApplication.UnicodeUTF8))
        self.probabilitiescheckbox.setObjectName(_fromUtf8("probabilitiescheckbox"))
        self.steadystatecheckbox = QtGui.QCheckBox(self.outputgroupbox)
        self.steadystatecheckbox.setGeometry(QtCore.QRect(20, 50, 141, 16))
        self.steadystatecheckbox.setText(QtGui.QApplication.translate("spatial_dynamics", "Steady State Distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.steadystatecheckbox.setObjectName(_fromUtf8("steadystatecheckbox"))
        self.firstcheckbox = QtGui.QCheckBox(self.outputgroupbox)
        self.firstcheckbox.setGeometry(QtCore.QRect(200, 50, 151, 16))
        self.firstcheckbox.setText(QtGui.QApplication.translate("spatial_dynamics", "First Mean Passage Time", None, QtGui.QApplication.UnicodeUTF8))
        self.firstcheckbox.setObjectName(_fromUtf8("firstcheckbox"))
        self.saveoutputbutton = QtGui.QPushButton(self.outputgroupbox)
        self.saveoutputbutton.setGeometry(QtCore.QRect(340, 80, 31, 23))
        self.saveoutputbutton.setText(QtGui.QApplication.translate("spatial_dynamics", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.saveoutputbutton.setObjectName(_fromUtf8("saveoutputbutton"))
        self.saveoutputlabel = QtGui.QLabel(self.outputgroupbox)
        self.saveoutputlabel.setGeometry(QtCore.QRect(20, 80, 81, 16))
        self.saveoutputlabel.setText(QtGui.QApplication.translate("spatial_dynamics", "Save Output as", None, QtGui.QApplication.UnicodeUTF8))
        self.saveoutputlabel.setObjectName(_fromUtf8("saveoutputlabel"))
        self.saveoutputline = QtGui.QLineEdit(self.outputgroupbox)
        self.saveoutputline.setGeometry(QtCore.QRect(100, 80, 231, 20))
        self.saveoutputline.setObjectName(_fromUtf8("saveoutputline"))
        self.buttonBox = QtGui.QDialogButtonBox(spatial_dynamics)
        self.buttonBox.setGeometry(QtCore.QRect(240, 510, 156, 23))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label = QtGui.QLabel(spatial_dynamics)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.label.setFont(font)
        self.label.setText(QtGui.QApplication.translate("spatial_dynamics", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'新細明體\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Spatial Markovs</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox = QtGui.QGroupBox(spatial_dynamics)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 381, 181))
        self.groupBox.setTitle(QtGui.QApplication.translate("spatial_dynamics", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.inputbutton = QtGui.QPushButton(self.groupBox)
        self.inputbutton.setGeometry(QtCore.QRect(340, 90, 31, 23))
        self.inputbutton.setText(QtGui.QApplication.translate("spatial_dynamics", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.inputbutton.setObjectName(_fromUtf8("inputbutton"))
        self.inputline = QtGui.QLineEdit(self.groupBox)
        self.inputline.setGeometry(QtCore.QRect(100, 90, 231, 20))
        self.inputline.setObjectName(_fromUtf8("inputline"))
        self.savedshpradio = QtGui.QRadioButton(self.groupBox)
        self.savedshpradio.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.savedshpradio.setText(QtGui.QApplication.translate("spatial_dynamics", "Saved ShapeFile", None, QtGui.QApplication.UnicodeUTF8))
        self.savedshpradio.setObjectName(_fromUtf8("savedshpradio"))
        self.inputshplabel = QtGui.QLabel(self.groupBox)
        self.inputshplabel.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.inputshplabel.setText(QtGui.QApplication.translate("spatial_dynamics", "Input ShapeFile", None, QtGui.QApplication.UnicodeUTF8))
        self.inputshplabel.setObjectName(_fromUtf8("inputshplabel"))
        self.activeradio = QtGui.QRadioButton(self.groupBox)
        self.activeradio.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.activeradio.setText(QtGui.QApplication.translate("spatial_dynamics", "Active Layer in map", None, QtGui.QApplication.UnicodeUTF8))
        self.activeradio.setObjectName(_fromUtf8("activeradio"))
        self.activecombobox = QtGui.QComboBox(self.groupBox)
        self.activecombobox.setGeometry(QtCore.QRect(140, 30, 231, 22))
        self.activecombobox.setObjectName(_fromUtf8("activecombobox"))
        self.startyear = QtGui.QLabel(self.groupBox)
        self.startyear.setGeometry(QtCore.QRect(20, 120, 81, 16))
        self.startyear.setText(QtGui.QApplication.translate("spatial_dynamics", "Start Year", None, QtGui.QApplication.UnicodeUTF8))
        self.startyear.setObjectName(_fromUtf8("startyear"))
        self.startcombobox = QtGui.QComboBox(self.groupBox)
        self.startcombobox.setGeometry(QtCore.QRect(100, 120, 231, 22))
        self.startcombobox.setObjectName(_fromUtf8("startcombobox"))
        self.endyear = QtGui.QLabel(self.groupBox)
        self.endyear.setGeometry(QtCore.QRect(20, 150, 81, 16))
        self.endyear.setText(QtGui.QApplication.translate("spatial_dynamics", "End Year", None, QtGui.QApplication.UnicodeUTF8))
        self.endyear.setObjectName(_fromUtf8("endyear"))
        self.endcombobox = QtGui.QComboBox(self.groupBox)
        self.endcombobox.setGeometry(QtCore.QRect(100, 150, 231, 22))
        self.endcombobox.setObjectName(_fromUtf8("endcombobox"))
        self.datagroupbox = QtGui.QGroupBox(spatial_dynamics)
        self.datagroupbox.setGeometry(QtCore.QRect(10, 220, 381, 111))
        self.datagroupbox.setTitle(QtGui.QApplication.translate("spatial_dynamics", "Data Processing", None, QtGui.QApplication.UnicodeUTF8))
        self.datagroupbox.setObjectName(_fromUtf8("datagroupbox"))
        self.classlabel = QtGui.QLabel(self.datagroupbox)
        self.classlabel.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.classlabel.setText(QtGui.QApplication.translate("spatial_dynamics", "Classification", None, QtGui.QApplication.UnicodeUTF8))
        self.classlabel.setObjectName(_fromUtf8("classlabel"))
        self.standardlabel = QtGui.QLabel(self.datagroupbox)
        self.standardlabel.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.standardlabel.setText(QtGui.QApplication.translate("spatial_dynamics", "Standardization", None, QtGui.QApplication.UnicodeUTF8))
        self.standardlabel.setObjectName(_fromUtf8("standardlabel"))
        self.savedatalabel = QtGui.QLabel(self.datagroupbox)
        self.savedatalabel.setGeometry(QtCore.QRect(20, 80, 81, 16))
        self.savedatalabel.setText(QtGui.QApplication.translate("spatial_dynamics", "Save Output as", None, QtGui.QApplication.UnicodeUTF8))
        self.savedatalabel.setObjectName(_fromUtf8("savedatalabel"))
        self.classcombobox = QtGui.QComboBox(self.datagroupbox)
        self.classcombobox.setGeometry(QtCore.QRect(110, 20, 231, 22))
        self.classcombobox.setObjectName(_fromUtf8("classcombobox"))
        self.classcombobox.addItem(_fromUtf8(""))
        self.classcombobox.setItemText(0, QtGui.QApplication.translate("spatial_dynamics", "Box_Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.classcombobox.addItem(_fromUtf8(""))
        self.classcombobox.setItemText(1, QtGui.QApplication.translate("spatial_dynamics", "Equal_Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.classcombobox.addItem(_fromUtf8(""))
        self.classcombobox.setItemText(2, QtGui.QApplication.translate("spatial_dynamics", "Fisher_Jenks", None, QtGui.QApplication.UnicodeUTF8))
        self.classcombobox.addItem(_fromUtf8(""))
        self.classcombobox.setItemText(3, QtGui.QApplication.translate("spatial_dynamics", "Jenks_Caspall", None, QtGui.QApplication.UnicodeUTF8))
        self.classcombobox.addItem(_fromUtf8(""))
        self.classcombobox.setItemText(4, QtGui.QApplication.translate("spatial_dynamics", "Jenks_Caspall_Forced", None, QtGui.QApplication.UnicodeUTF8))
        self.classcombobox.addItem(_fromUtf8(""))
        self.classcombobox.setItemText(5, QtGui.QApplication.translate("spatial_dynamics", "Jenks_Caspall_Sampled", None, QtGui.QApplication.UnicodeUTF8))
        self.classcombobox.addItem(_fromUtf8(""))
        self.classcombobox.setItemText(6, QtGui.QApplication.translate("spatial_dynamics", "Max_P_Classifier", None, QtGui.QApplication.UnicodeUTF8))
        self.classcombobox.addItem(_fromUtf8(""))
        self.classcombobox.setItemText(7, QtGui.QApplication.translate("spatial_dynamics", "Maximum_Breaks", None, QtGui.QApplication.UnicodeUTF8))
        self.classcombobox.addItem(_fromUtf8(""))
        self.classcombobox.setItemText(8, QtGui.QApplication.translate("spatial_dynamics", "Natural_Breaks", None, QtGui.QApplication.UnicodeUTF8))
        self.classcombobox.addItem(_fromUtf8(""))
        self.classcombobox.setItemText(9, QtGui.QApplication.translate("spatial_dynamics", "Quantiles", None, QtGui.QApplication.UnicodeUTF8))
        self.classcombobox.addItem(_fromUtf8(""))
        self.classcombobox.setItemText(10, QtGui.QApplication.translate("spatial_dynamics", "Percentiles", None, QtGui.QApplication.UnicodeUTF8))
        self.classcombobox.addItem(_fromUtf8(""))
        self.classcombobox.setItemText(11, QtGui.QApplication.translate("spatial_dynamics", "Std_Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.classcombobox.addItem(_fromUtf8(""))
        self.classcombobox.setItemText(12, QtGui.QApplication.translate("spatial_dynamics", "User_Defined", None, QtGui.QApplication.UnicodeUTF8))
        self.classcombobox.addItem(_fromUtf8(""))
        self.classcombobox.setItemText(13, QtGui.QApplication.translate("spatial_dynamics", "gadf", None, QtGui.QApplication.UnicodeUTF8))
        self.classcombobox.addItem(_fromUtf8(""))
        self.classcombobox.setItemText(14, QtGui.QApplication.translate("spatial_dynamics", "K_classifiers", None, QtGui.QApplication.UnicodeUTF8))
        self.standardcombobox = QtGui.QComboBox(self.datagroupbox)
        self.standardcombobox.setGeometry(QtCore.QRect(110, 50, 69, 22))
        self.standardcombobox.setObjectName(_fromUtf8("standardcombobox"))
        self.standardcombobox.addItem(_fromUtf8(""))
        self.standardcombobox.setItemText(0, QtGui.QApplication.translate("spatial_dynamics", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.standardcombobox.addItem(_fromUtf8(""))
        self.standardcombobox.setItemText(1, QtGui.QApplication.translate("spatial_dynamics", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.savedatabutton = QtGui.QPushButton(self.datagroupbox)
        self.savedatabutton.setGeometry(QtCore.QRect(340, 80, 31, 23))
        self.savedatabutton.setText(QtGui.QApplication.translate("spatial_dynamics", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.savedatabutton.setObjectName(_fromUtf8("savedatabutton"))
        self.savedataline = QtGui.QLineEdit(self.datagroupbox)
        self.savedataline.setGeometry(QtCore.QRect(110, 80, 221, 20))
        self.savedataline.setObjectName(_fromUtf8("savedataline"))

        self.retranslateUi(spatial_dynamics)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), spatial_dynamics.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), spatial_dynamics.reject)
        QtCore.QObject.connect(self.activeradio, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.inputline.setDisabled)
        QtCore.QObject.connect(self.activeradio, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.inputbutton.setDisabled)
        QtCore.QObject.connect(self.savedshpradio, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.activecombobox.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(spatial_dynamics)

    def retranslateUi(self, spatial_dynamics):
        pass

