# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_weights.ui'
#
# Created: Tue Oct 25 00:09:11 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Weights(object):
    def setupUi(self, Weights):
        Weights.setObjectName(_fromUtf8("Weights"))
        Weights.setWindowModality(QtCore.Qt.NonModal)
        Weights.resize(370, 428)
        Weights.setAcceptDrops(True)
        Weights.setWindowTitle(QtGui.QApplication.translate("Weights", "Weights Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBox = QtGui.QDialogButtonBox(Weights)
        self.buttonBox.setGeometry(QtCore.QRect(210, 400, 156, 23))
        self.buttonBox.setToolTip(QtGui.QApplication.translate("Weights", "press OK to render current raster", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label_3 = QtGui.QLabel(Weights)
        self.label_3.setGeometry(QtCore.QRect(9, 9, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("Weights", "Spatial Weights Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.groupBox = QtGui.QGroupBox(Weights)
        self.groupBox.setGeometry(QtCore.QRect(10, 250, 351, 131))
        self.groupBox.setTitle(QtGui.QApplication.translate("Weights", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 70, 331, 56))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 13))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Weights", "Output Location", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setText(QtGui.QApplication.translate("Weights", "Output File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.outputFile = QtGui.QLineEdit(self.groupBox_2)
        self.outputFile.setEnabled(True)
        self.outputFile.setToolTip(QtGui.QApplication.translate("Weights", "Select a directory where the computed weight matrix will be saved to.", None, QtGui.QApplication.UnicodeUTF8))
        self.outputFile.setObjectName(_fromUtf8("outputFile"))
        self.gridLayout.addWidget(self.outputFile, 0, 1, 1, 1)
        self.pbnOutput = QtGui.QPushButton(self.groupBox_2)
        self.pbnOutput.setEnabled(True)
        self.pbnOutput.setText(QtGui.QApplication.translate("Weights", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnOutput.setObjectName(_fromUtf8("pbnOutput"))
        self.gridLayout.addWidget(self.pbnOutput, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(12, 25, 76, 16))
        self.label.setText(QtGui.QApplication.translate("Weights", "Output File Ext.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.outputExt = QtGui.QComboBox(self.groupBox)
        self.outputExt.setGeometry(QtCore.QRect(12, 44, 49, 20))
        self.outputExt.setObjectName(_fromUtf8("outputExt"))
        self.outputExt.addItem(_fromUtf8(""))
        self.outputExt.setItemText(0, QtGui.QApplication.translate("Weights", "GAL", None, QtGui.QApplication.UnicodeUTF8))
        self.outputExt.addItem(_fromUtf8(""))
        self.outputExt.setItemText(1, QtGui.QApplication.translate("Weights", "GWT", None, QtGui.QApplication.UnicodeUTF8))
        self.outputExt.addItem(_fromUtf8(""))
        self.outputExt.setItemText(2, QtGui.QApplication.translate("Weights", "MAT", None, QtGui.QApplication.UnicodeUTF8))
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(130, 24, 211, 42))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.addNumNeighbors = QtGui.QCheckBox(self.widget)
        self.addNumNeighbors.setText(QtGui.QApplication.translate("Weights", "Add number of neighbors field to shp", None, QtGui.QApplication.UnicodeUTF8))
        self.addNumNeighbors.setObjectName(_fromUtf8("addNumNeighbors"))
        self.verticalLayout.addWidget(self.addNumNeighbors)
        self.addY = QtGui.QCheckBox(self.widget)
        self.addY.setText(QtGui.QApplication.translate("Weights", "Add Y as Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.addY.setObjectName(_fromUtf8("addY"))
        self.verticalLayout.addWidget(self.addY)
        self.inputBox = QtGui.QGroupBox(Weights)
        self.inputBox.setGeometry(QtCore.QRect(9, 28, 354, 102))
        self.inputBox.setTitle(QtGui.QApplication.translate("Weights", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.inputBox.setObjectName(_fromUtf8("inputBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.inputBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.rbUseActiveLayer = QtGui.QRadioButton(self.inputBox)
        self.rbUseActiveLayer.setText(QtGui.QApplication.translate("Weights", "Active layer in map", None, QtGui.QApplication.UnicodeUTF8))
        self.rbUseActiveLayer.setChecked(True)
        self.rbUseActiveLayer.setObjectName(_fromUtf8("rbUseActiveLayer"))
        self.buttonGroup = QtGui.QButtonGroup(Weights)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.rbUseActiveLayer)
        self.gridLayout_4.addWidget(self.rbUseActiveLayer, 0, 0, 1, 1)
        self.rbSaveShapefile = QtGui.QRadioButton(self.inputBox)
        self.rbSaveShapefile.setText(QtGui.QApplication.translate("Weights", "Saved shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.rbSaveShapefile.setObjectName(_fromUtf8("rbSaveShapefile"))
        self.buttonGroup.addButton(self.rbSaveShapefile)
        self.gridLayout_4.addWidget(self.rbSaveShapefile, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.inputBox)
        self.label_8.setText(QtGui.QApplication.translate("Weights", "Input Shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.inputFile = QtGui.QLineEdit(self.inputBox)
        self.inputFile.setEnabled(False)
        self.inputFile.setToolTip(QtGui.QApplication.translate("Weights", "Choose a shapefile from which to create the spatial weights matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.inputFile.setObjectName(_fromUtf8("inputFile"))
        self.gridLayout_4.addWidget(self.inputFile, 2, 1, 1, 1)
        self.pbnInput = QtGui.QPushButton(self.inputBox)
        self.pbnInput.setEnabled(False)
        self.pbnInput.setText(QtGui.QApplication.translate("Weights", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnInput.setObjectName(_fromUtf8("pbnInput"))
        self.gridLayout_4.addWidget(self.pbnInput, 2, 2, 1, 1)
        self.sourceLayer = QtGui.QComboBox(self.inputBox)
        self.sourceLayer.setObjectName(_fromUtf8("sourceLayer"))
        self.gridLayout_4.addWidget(self.sourceLayer, 0, 1, 1, 2)
        self.optionBox = QtGui.QGroupBox(Weights)
        self.optionBox.setGeometry(QtCore.QRect(10, 140, 354, 102))
        self.optionBox.setTitle(QtGui.QApplication.translate("Weights", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.optionBox.setObjectName(_fromUtf8("optionBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.optionBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.rbDistance = QtGui.QRadioButton(self.optionBox)
        self.rbDistance.setText(QtGui.QApplication.translate("Weights", "Distance-Based", None, QtGui.QApplication.UnicodeUTF8))
        self.rbDistance.setObjectName(_fromUtf8("rbDistance"))
        self.gridLayout_5.addWidget(self.rbDistance, 1, 0, 1, 1)
        self.contComboBox = QtGui.QComboBox(self.optionBox)
        self.contComboBox.setObjectName(_fromUtf8("contComboBox"))
        self.contComboBox.addItem(_fromUtf8(""))
        self.contComboBox.setItemText(0, QtGui.QApplication.translate("Weights", "Rook", None, QtGui.QApplication.UnicodeUTF8))
        self.contComboBox.addItem(_fromUtf8(""))
        self.contComboBox.setItemText(1, QtGui.QApplication.translate("Weights", "Queen", None, QtGui.QApplication.UnicodeUTF8))
        self.contComboBox.addItem(_fromUtf8(""))
        self.contComboBox.setItemText(2, QtGui.QApplication.translate("Weights", "Bishop", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_5.addWidget(self.contComboBox, 0, 1, 1, 2)
        self.rbContiguity = QtGui.QRadioButton(self.optionBox)
        self.rbContiguity.setText(QtGui.QApplication.translate("Weights", "Contiguity", None, QtGui.QApplication.UnicodeUTF8))
        self.rbContiguity.setObjectName(_fromUtf8("rbContiguity"))
        self.gridLayout_5.addWidget(self.rbContiguity, 0, 0, 1, 1)
        self.distMethod = QtGui.QComboBox(self.optionBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distMethod.sizePolicy().hasHeightForWidth())
        self.distMethod.setSizePolicy(sizePolicy)
        self.distMethod.setObjectName(_fromUtf8("distMethod"))
        self.distMethod.addItem(_fromUtf8(""))
        self.distMethod.setItemText(0, QtGui.QApplication.translate("Weights", "K Nearest Neighbors", None, QtGui.QApplication.UnicodeUTF8))
        self.distMethod.addItem(_fromUtf8(""))
        self.distMethod.setItemText(1, QtGui.QApplication.translate("Weights", "r Nearest Neighbors", None, QtGui.QApplication.UnicodeUTF8))
        self.distMethod.addItem(_fromUtf8(""))
        self.distMethod.setItemText(2, QtGui.QApplication.translate("Weights", "Euclidean", None, QtGui.QApplication.UnicodeUTF8))
        self.distMethod.addItem(_fromUtf8(""))
        self.distMethod.setItemText(3, QtGui.QApplication.translate("Weights", "Manhattan", None, QtGui.QApplication.UnicodeUTF8))
        self.distMethod.addItem(_fromUtf8(""))
        self.distMethod.setItemText(4, QtGui.QApplication.translate("Weights", "Max nn-distance Band", None, QtGui.QApplication.UnicodeUTF8))
        self.distMethod.addItem(_fromUtf8(""))
        self.distMethod.setItemText(5, QtGui.QApplication.translate("Weights", "I just kept listing slides from Serge", None, QtGui.QApplication.UnicodeUTF8))
        self.distMethod.addItem(_fromUtf8(""))
        self.distMethod.setItemText(6, QtGui.QApplication.translate("Weights", "What fits/doesn\'t fit here", None, QtGui.QApplication.UnicodeUTF8))
        self.distMethod.addItem(_fromUtf8(""))
        self.distMethod.setItemText(7, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.distMethod, 1, 2, 1, 1)
        self.inputDistance = QtGui.QLineEdit(self.optionBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputDistance.sizePolicy().hasHeightForWidth())
        self.inputDistance.setSizePolicy(sizePolicy)
        self.inputDistance.setObjectName(_fromUtf8("inputDistance"))
        self.gridLayout_5.addWidget(self.inputDistance, 1, 1, 1, 1)
        self.label_9.setBuddy(self.outputFile)
        self.label_8.setBuddy(self.inputFile)

        self.retranslateUi(Weights)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Weights.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Weights.accept)
        QtCore.QObject.connect(self.rbUseActiveLayer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.inputFile.setDisabled)
        QtCore.QObject.connect(self.rbSaveShapefile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbnInput.setEnabled)
        QtCore.QObject.connect(self.rbSaveShapefile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbnOutput.setEnabled)
        QtCore.QObject.connect(self.rbUseActiveLayer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbnInput.setDisabled)
        QtCore.QObject.connect(self.rbUseActiveLayer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sourceLayer.setEnabled)
        QtCore.QObject.connect(self.rbSaveShapefile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sourceLayer.setDisabled)
        QtCore.QObject.connect(self.rbContiguity, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.inputDistance.setDisabled)
        QtCore.QObject.connect(self.rbContiguity, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.distMethod.setDisabled)
        QtCore.QObject.connect(self.rbContiguity, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.contComboBox.setEnabled)
        QtCore.QObject.connect(self.rbDistance, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.contComboBox.setDisabled)
        QtCore.QObject.connect(self.rbDistance, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.distMethod.setEnabled)
        QtCore.QObject.connect(self.rbDistance, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.inputDistance.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Weights)
        Weights.setTabOrder(self.rbUseActiveLayer, self.rbSaveShapefile)
        Weights.setTabOrder(self.rbSaveShapefile, self.inputFile)
        Weights.setTabOrder(self.inputFile, self.pbnInput)
        Weights.setTabOrder(self.pbnInput, self.buttonBox)

    def retranslateUi(self, Weights):
        pass

