# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_weights.ui'
#
# Created: Tue Nov 29 01:51:53 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Weights(object):
    def setupUi(self, Weights):
        Weights.setObjectName(_fromUtf8("Weights"))
        Weights.setWindowModality(QtCore.Qt.WindowModal)
        Weights.setEnabled(True)
        Weights.resize(368, 488)
        Weights.setAcceptDrops(True)
        Weights.setWindowTitle(QtGui.QApplication.translate("Weights", "Weights Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_6 = QtGui.QGridLayout(Weights)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_3 = QtGui.QLabel(Weights)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("Weights", "Spatial Weights Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.inputBox = QtGui.QGroupBox(Weights)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputBox.sizePolicy().hasHeightForWidth())
        self.inputBox.setSizePolicy(sizePolicy)
        self.inputBox.setTitle(QtGui.QApplication.translate("Weights", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.inputBox.setObjectName(_fromUtf8("inputBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.inputBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.rbUseActiveLayer = QtGui.QRadioButton(self.inputBox)
        self.rbUseActiveLayer.setText(QtGui.QApplication.translate("Weights", "Active layer in map", None, QtGui.QApplication.UnicodeUTF8))
        self.rbUseActiveLayer.setChecked(True)
        self.rbUseActiveLayer.setObjectName(_fromUtf8("rbUseActiveLayer"))
        self.buttonGroup = QtGui.QButtonGroup(Weights)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.rbUseActiveLayer)
        self.gridLayout_4.addWidget(self.rbUseActiveLayer, 0, 0, 1, 1)
        self.sourceLayer = QtGui.QComboBox(self.inputBox)
        self.sourceLayer.setObjectName(_fromUtf8("sourceLayer"))
        self.gridLayout_4.addWidget(self.sourceLayer, 0, 1, 1, 2)
        self.rbSaveShapefile = QtGui.QRadioButton(self.inputBox)
        self.rbSaveShapefile.setText(QtGui.QApplication.translate("Weights", "Saved shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.rbSaveShapefile.setObjectName(_fromUtf8("rbSaveShapefile"))
        self.buttonGroup.addButton(self.rbSaveShapefile)
        self.gridLayout_4.addWidget(self.rbSaveShapefile, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.inputBox)
        self.label_8.setText(QtGui.QApplication.translate("Weights", "Input Shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.inputFile = QtGui.QLineEdit(self.inputBox)
        self.inputFile.setEnabled(False)
        self.inputFile.setToolTip(QtGui.QApplication.translate("Weights", "Choose a shapefile from which to create the spatial weights matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.inputFile.setObjectName(_fromUtf8("inputFile"))
        self.gridLayout_4.addWidget(self.inputFile, 2, 1, 1, 1)
        self.pbnInput = QtGui.QPushButton(self.inputBox)
        self.pbnInput.setEnabled(False)
        self.pbnInput.setText(QtGui.QApplication.translate("Weights", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnInput.setObjectName(_fromUtf8("pbnInput"))
        self.gridLayout_4.addWidget(self.pbnInput, 2, 2, 1, 1)
        self.gridLayout_6.addWidget(self.inputBox, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Weights)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle(QtGui.QApplication.translate("Weights", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.addNumNeighbors = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addNumNeighbors.sizePolicy().hasHeightForWidth())
        self.addNumNeighbors.setSizePolicy(sizePolicy)
        self.addNumNeighbors.setText(QtGui.QApplication.translate("Weights", "Add number of neighbors field to shp", None, QtGui.QApplication.UnicodeUTF8))
        self.addNumNeighbors.setObjectName(_fromUtf8("addNumNeighbors"))
        self.verticalLayout.addWidget(self.addNumNeighbors)
        self.addY = QtGui.QCheckBox(self.groupBox)
        self.addY.setText(QtGui.QApplication.translate("Weights", "Add Y as Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.addY.setObjectName(_fromUtf8("addY"))
        self.verticalLayout.addWidget(self.addY)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 13))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Weights", "Output Location", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setText(QtGui.QApplication.translate("Weights", "Output File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.outputFile = QtGui.QLineEdit(self.groupBox_2)
        self.outputFile.setEnabled(True)
        self.outputFile.setToolTip(QtGui.QApplication.translate("Weights", "Select a directory where the computed weight matrix will be saved to.", None, QtGui.QApplication.UnicodeUTF8))
        self.outputFile.setObjectName(_fromUtf8("outputFile"))
        self.gridLayout.addWidget(self.outputFile, 0, 1, 1, 1)
        self.pbnOutput = QtGui.QPushButton(self.groupBox_2)
        self.pbnOutput.setEnabled(True)
        self.pbnOutput.setText(QtGui.QApplication.translate("Weights", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnOutput.setObjectName(_fromUtf8("pbnOutput"))
        self.gridLayout.addWidget(self.pbnOutput, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout_6.addWidget(self.groupBox, 3, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Weights)
        self.buttonBox.setToolTip(QtGui.QApplication.translate("Weights", "press OK to render current raster", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_6.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.optionBox = QtGui.QGroupBox(Weights)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionBox.sizePolicy().hasHeightForWidth())
        self.optionBox.setSizePolicy(sizePolicy)
        self.optionBox.setTitle(QtGui.QApplication.translate("Weights", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.optionBox.setObjectName(_fromUtf8("optionBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.optionBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.rbContiguity = QtGui.QRadioButton(self.optionBox)
        self.rbContiguity.setEnabled(True)
        self.rbContiguity.setText(QtGui.QApplication.translate("Weights", "Contiguity", None, QtGui.QApplication.UnicodeUTF8))
        self.rbContiguity.setObjectName(_fromUtf8("rbContiguity"))
        self.gridLayout_5.addWidget(self.rbContiguity, 1, 0, 1, 1)
        self.contComboBox = QtGui.QComboBox(self.optionBox)
        self.contComboBox.setEnabled(False)
        self.contComboBox.setObjectName(_fromUtf8("contComboBox"))
        self.contComboBox.addItem(_fromUtf8(""))
        self.contComboBox.setItemText(0, QtGui.QApplication.translate("Weights", "Rook", None, QtGui.QApplication.UnicodeUTF8))
        self.contComboBox.addItem(_fromUtf8(""))
        self.contComboBox.setItemText(1, QtGui.QApplication.translate("Weights", "Queen", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_5.addWidget(self.contComboBox, 1, 1, 1, 2)
        self.stackedWidget = QtGui.QStackedWidget(self.optionBox)
        self.stackedWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setMidLineWidth(0)
        self.stackedWidget.setProperty("hidden", True)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.th = QtGui.QWidget()
        self.th.setObjectName(_fromUtf8("th"))
        self.gridLayout_7 = QtGui.QGridLayout(self.th)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_4 = QtGui.QLabel(self.th)
        self.label_4.setEnabled(True)
        self.label_4.setText(QtGui.QApplication.translate("Weights", "Threshhold Distance ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)
        self.threshDist = QtGui.QLineEdit(self.th)
        self.threshDist.setObjectName(_fromUtf8("threshDist"))
        self.gridLayout_7.addWidget(self.threshDist, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.th)
        self.inv = QtGui.QWidget()
        self.inv.setObjectName(_fromUtf8("inv"))
        self.gridLayout_3 = QtGui.QGridLayout(self.inv)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.invDist = QtGui.QLineEdit(self.inv)
        self.invDist.setObjectName(_fromUtf8("invDist"))
        self.gridLayout_3.addWidget(self.invDist, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.inv)
        self.label_2.setText(QtGui.QApplication.translate("Weights", "Inverse  Distance     ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.inv)
        self.knn = QtGui.QWidget()
        self.knn.setObjectName(_fromUtf8("knn"))
        self.gridLayout_2 = QtGui.QGridLayout(self.knn)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.knn)
        self.groupBox_3.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(False)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setEnabled(True)
        self.label.setText(QtGui.QApplication.translate("Weights", "# Neighbors", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.inputDistance = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputDistance.sizePolicy().hasHeightForWidth())
        self.inputDistance.setSizePolicy(sizePolicy)
        self.inputDistance.setText(QtGui.QApplication.translate("Weights", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.inputDistance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputDistance.setObjectName(_fromUtf8("inputDistance"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.inputDistance)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.horizontalSlider = QtGui.QSlider(self.knn)
        self.horizontalSlider.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.horizontalSlider.setTickInterval(10)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.gridLayout_2.addWidget(self.horizontalSlider, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.knn)
        self.gridLayout_5.addWidget(self.stackedWidget, 3, 0, 1, 3)
        self.rbDistance = QtGui.QRadioButton(self.optionBox)
        self.rbDistance.setText(QtGui.QApplication.translate("Weights", "Distance-Based", None, QtGui.QApplication.UnicodeUTF8))
        self.rbDistance.setChecked(True)
        self.rbDistance.setObjectName(_fromUtf8("rbDistance"))
        self.gridLayout_5.addWidget(self.rbDistance, 0, 0, 1, 1)
        self.distMethod = QtGui.QComboBox(self.optionBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distMethod.sizePolicy().hasHeightForWidth())
        self.distMethod.setSizePolicy(sizePolicy)
        self.distMethod.setObjectName(_fromUtf8("distMethod"))
        self.distMethod.addItem(_fromUtf8(""))
        self.distMethod.setItemText(0, QtGui.QApplication.translate("Weights", "Threshhold Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.distMethod.addItem(_fromUtf8(""))
        self.distMethod.setItemText(1, QtGui.QApplication.translate("Weights", "Inverse Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.distMethod.addItem(_fromUtf8(""))
        self.distMethod.setItemText(2, QtGui.QApplication.translate("Weights", "K Nearest Neighbors", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_5.addWidget(self.distMethod, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.optionBox, 2, 0, 1, 1)
        self.label_8.setBuddy(self.inputFile)
        self.label_9.setBuddy(self.outputFile)

        self.retranslateUi(Weights)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Weights.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Weights.accept)
        QtCore.QObject.connect(self.rbUseActiveLayer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.inputFile.setDisabled)
        QtCore.QObject.connect(self.rbSaveShapefile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbnInput.setEnabled)
        QtCore.QObject.connect(self.rbSaveShapefile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbnOutput.setEnabled)
        QtCore.QObject.connect(self.rbUseActiveLayer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbnInput.setDisabled)
        QtCore.QObject.connect(self.rbUseActiveLayer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sourceLayer.setEnabled)
        QtCore.QObject.connect(self.rbSaveShapefile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sourceLayer.setDisabled)
        QtCore.QObject.connect(self.rbContiguity, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.distMethod.setDisabled)
        QtCore.QObject.connect(self.rbContiguity, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.contComboBox.setEnabled)
        QtCore.QObject.connect(self.rbDistance, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.contComboBox.setDisabled)
        QtCore.QObject.connect(self.rbDistance, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.distMethod.setEnabled)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.inputDistance.setNum)
        QtCore.QObject.connect(self.rbContiguity, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.stackedWidget.hide)
        QtCore.QObject.connect(self.distMethod, QtCore.SIGNAL(_fromUtf8("activated(int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QObject.connect(self.rbDistance, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.stackedWidget.show)
        QtCore.QMetaObject.connectSlotsByName(Weights)
        Weights.setTabOrder(self.rbUseActiveLayer, self.rbSaveShapefile)
        Weights.setTabOrder(self.rbSaveShapefile, self.inputFile)
        Weights.setTabOrder(self.inputFile, self.pbnInput)
        Weights.setTabOrder(self.pbnInput, self.buttonBox)

    def retranslateUi(self, Weights):
        pass

